/* Copyright (c) 2026 Dmitri Arekhta. All rights reserved. */
#ifndef NTFS_TEST_FIXTURE_H
#define NTFS_TEST_FIXTURE_H

/* Consumer expectations for the independently authored Python images. These
 * describe fixture geometry and payloads, not parser implementation details. */
enum {
	TEST_SECTOR_BYTES = 512,
	TEST_CLUSTER_BYTES = 4096,
	TEST_PHYSICAL_BLOCK_BYTES = 4096,
	TEST_MFT_RECORD_BYTES = 1024,
	TEST_IMAGE_BYTES = 8 * 1024 * 1024,
	TEST_ALLOCATED_CLUSTERS = 160,
	TEST_FILE_COUNT = 9,
	TEST_SECURITY_ID = 256,
	TEST_PATTERN_MULTIPLIER = 13,
	TEST_PATTERN_ADDEND = 7,
	TEST_FRAGMENTED_BYTES = 6000,
	TEST_INITIALIZED_BYTES = 100,
	TEST_COMPRESSION_CLUSTERS = 16,
	TEST_COMPRESSION_UNIT_BYTES = TEST_CLUSTER_BYTES * TEST_COMPRESSION_CLUSTERS,
	TEST_READ_WINDOW_BYTES = TEST_SECTOR_BYTES + 1,
	TEST_CROSS_CLUSTER_PREFIX_BYTES = 6,
	TEST_CONCURRENT_READS = 64,
	TEST_DIRECTORY_BATCH_CAPACITY = 2,
	TEST_INVALIDATE_REPETITIONS = 3
};

#define TEST_LARGE_SPARSE_BYTES (UINT64_C(8) * 1024 * 1024 * 1024)

#endif
